dist: trusty

language: python

services:
  - postgresql

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
# Removed because linting PR coming up separately
#  - LINT="yes"
  - DJANGO="1.9" CRYPTOGRAPHY="1.2"
  # - DJANGO="1.9" CRYPTOGRAPHY="1.8"
  # - DJANGO="1.9" CRYPTOGRAPHY="2.0"
  # - DJANGO="1.10" CRYPTOGRAPHY="1.2"
  # - DJANGO="1.10" CRYPTOGRAPHY="1.8"
  # - DJANGO="1.10" CRYPTOGRAPHY="2.0"
  # - DJANGO="1.11" CRYPTOGRAPHY="1.2"
  # - DJANGO="1.11" CRYPTOGRAPHY="1.8"
  # - DJANGO="1.11" CRYPTOGRAPHY="2.0"

matrix:
  include:
    - python: "3.5"
      env:
        - TOX_ENV=postgres
  exclude:
  - python: "2.7"
    env: DJANGO="1.9" CRYPTOGRAPHY="1.2"
  - python: "2.7"
    env: DJANGO="1.10" CRYPTOGRAPHY="1.2"
  - python: "3.4"
    env: LINT="yes"
  - python: "3.4"
    env: DJANGO="1.9" CRYPTOGRAPHY="1.2"
  - python: "3.4"
    env: DJANGO="1.10" CRYPTOGRAPHY="1.2"
  - python: "3.4"
    env: DJANGO="1.11" CRYPTOGRAPHY="1.2"
  - python: "3.5"
    env: LINT="yes"
  - python: "3.5"
    env: DJANGO="1.9" CRYPTOGRAPHY="1.2"
  - python: "3.5"
    env: DJANGO="1.10" CRYPTOGRAPHY="1.2"
  - python: "3.5"
    env: DJANGO="1.11" CRYPTOGRAPHY="1.2"
  - python: "3.6"
    env: LINT="yes"
  - python: "3.6"
    env: DJANGO="1.9" CRYPTOGRAPHY="1.2"
  - python: "3.6"
    env: DJANGO="1.9" CRYPTOGRAPHY="2.0"
  - python: "3.6"
    env: DJANGO="1.10" CRYPTOGRAPHY="1.2"
  - python: "3.6"
    env: DJANGO="1.10" CRYPTOGRAPHY="2.0"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - pip install tox tox-travis codecov

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV

after_success:
  - coverage combine
  - codecov

